### ISSUE TITLE
cannot run 

### ISSUE THREAD

**Issue by dowcet** [drakedevel/gsclient#10]
I'm on Linux Mint 15, "python --version" says 2.7.4 and mplayer is working. 

When I run main.py, I get the following errors.

Traceback (most recent call last):
  File "main.py", line 184, in <module>
    MainCmd().cmdloop()
  File "main.py", line 28, in __init__
    self._client = gsclient.ClientWrapper()
  File "/home/brian/Desktop/gsclient-master/gsclient.py", line 41, in __init__
    self.new_session()
  File "/home/brian/Desktop/gsclient-master/gsclient.py", line 89, in new_session
    self._web.start_session()
  File "/home/brian/Desktop/gsclient-master/gs.py", line 101, in start_session
    self._service.session = self._send(req)
  File "/home/brian/Desktop/gsclient-master/gs.py", line 73, in _send
    return self._service.send(req, header)
  File "/home/brian/Desktop/gsclient-master/gs.py", line 54, in send
    data['fault']['code'])
gs.ServiceException: Server returned: invalid client (code 1024)

**Comment by drakedevel** [comment]
Closing since Grooveshark is now defunct
