### ISSUE TITLE
Select Command failure

### ISSUE THREAD

**Issue by koen-github** [drakedevel/gsclient#2]
Hi, 

Thanks for your great work! I could try your script about 4 times (very nice!), but now it doesn't work anymore when I type  select <sond_Id>, I get the following error:

```
gscmd> select 29
Traceback (most recent call last):
  File "main.py", line 156, in <module>
    MainCmd().cmdloop()
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "main.py", line 123, in do_select
    self._select(self._results[index - 1])
  File "main.py", line 130, in _select_song
    (url, postdata) = self._client.get_stream(song)
  File "/home/koen/gsclient-master/gsclient/gsclient.py", line 62, in get_stream
    print stream_data['streamKey']
TypeError: list indices must be integers, not str

```

**Comment by drakedevel** [comment]
Closing since Grooveshark is now defunct

**Comment by JoelOtter** [comment]
Thanks for your hard work on a great library, @drakedevel :+1:
